### ISSUE TITLE
All serial numbers will disappear except #### serial numbers which will not disappear

### ISSUE THREAD

**Issue by zhl111** [ryjjin/Obsidian-shortcuts-extender#12]
![image](https://user-images.githubusercontent.com/29135984/140649239-16046506-bc44-4c48-a2ec-d08dff787b48.png)

**Comment by ryjjin** [comment]
Hi! Sorry for long reply. 
I cannot reproduce this bug, in my case was always clear the formatting entirely before changing the state of the line. 

Can you say:
- what is your operating system?
- what exactly are you doing?

Just in case, try updating the plugin if suddenly your version is older than mine.

## What behavior have I tested 

### 1. take a numbered list as a source text, and change its heading levels.

From the text:

```md
1. Test
2. Test
3. Test
4. Test
5. Test
6. Test
```

It turned out the following: 

```md
# Test
## Test
### Test
#### Test
##### Test
###### Test
```

### 2. take numbered headings of different levels and clear their formatting

From the text:

```md
# 1. Test
## 2. Test
### 3. Test
#### 4. Test
##### 5. Test
###### 6. Test
```

I got:

```md
Test
Test
Test
Test
Test
Test
```

### 3. take numbered headings of different levels and change their heading level

From the text:

```md
# 1. Test
## 2. Test
### 3. Test
#### 4. Test
##### 5. Test
###### 6. Test
```

I got:

```md
###### Test
##### Test
#### Test
### Test
## Test
# Test
```

**Comment by ryjjin** [comment]
Given the code rework in terms of cleaning up the formatting and indicating the level of headers - even if this bug had some kind of special case, now it has most likely disappeared. Let me know if this case repeats.
